branches:
  only:
    - master

stages:
  - lint
  - build core
  - webpack core
  - tests

matrix:
  include:
    # Lint
    - stage: lint
      language: node_js
      os: linux
      node_js: "8"
      script:
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
    # Build Core App
    - stage: build core
      ## Android Build
      os: linux
      env:
        - OS="Android28"
      language: android
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd src && npm i && npm run tsc
        - cd ../demo && tns build android
    ## iOS Build
    - os: osx
      env:
        - OS="iOS12.0"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd src && npm i && npm run tsc
        - cd ../demo && tns build ios
    # Webpack Core App
    - stage: webpack core
      ## Android Webpack
      os: linux
      language: android
      env:
        - OS="Android28"
      jdk: oraclejdk8
      before_install: nvm install 8.11.4
      script:
        - cd demo && npm run build.plugin
        - npm i && tns build android --bundle --env.uglify
    ## iOS Webpack
    - os: osx
      env:
        - OS="iOS12.0"
        - Xcode="10.0"
      osx_image: xcode10
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      script:
        - cd demo && npm run build.plugin
        - npm i && tns build ios --bundle --env.uglify
    # Tests
    - stage: tests
      ## Android Test
      os: linux
      language: android
      dist: precise
      jdk: oraclejdk8
      env:
        - OS="Android28"
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8
      script:
        - cd src && npm i && npm run tsc && npm run tslint
        - cd ../demo && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    ## iOS Test
    - os: osx
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      env:
        - OS="iOS12.0"
        - Xcode="10.0"
      osx_image: xcode10
      script:
        - cd src && npm i && npm run tsc && npm run tslint
        - cd ../demo && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable
